baseURL = "https://tongxiaofeng.com/"
publishDir = "docs"
title = "佟晓峰"
LanguageCode = "zh-CN"
defaultContentLanguage = "zh"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-material-blog"

# Copyright, appears in the footer
copyright = "© 2019 Copyright 佟晓峰"

# Links format
[permalinks]
  post = "/:year/:month/:title/"

# 中文
[languages.zh]
  languageName = "中文"

  # Main menu
  [[languages.zh.menu.main]]
    url = "/"
    name = "主页"
    
  # Footer menu 1
  [[languages.zh.menu.footer1]]
    url = "/categories"
    name = "分类"
    weight = 1
  [[languages.zh.menu.footer1]]
    url = "/tags"
    name = "标签"
    weight = 2

  # Footer menu 2
  [[languages.zh.menu.footer2]]
    url = "/"
    name = "主页"
    weight = 1
  [[languages.zh.menu.footer2]]
    url = "/about"
    name = "关于"
    weight = 2

  # Include menus in footer
  #[[languages.zh.params.footer_menus]]
  #  name = "服务"
  #  menu = "footer2"
  #[[languages.zh.params.footer_menus]]
  #  name = "链接"
  #  menu = "footer1"

# English
[languages.en]
  languageName = "English"

  # Main menu
  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1

  # Footer menu 1
  #[[languages.en.menu.footer1]]
  #  url = "#"
  #  name = "Link 1"
  #  weight = 1
  #[[languages.en.menu.footer1]]
  #  url = "#"
  #  name = "Link 2"
  #  weight = 2

  # Footer menu 2
  #[[languages.en.menu.footer2]]
  #  url = "/"
  #  name = "Home"
  #  weight = 1
  #[[languages.en.menu.footer2]]
  #  url = "/about"
  #  name = "About"
  #  weight = 2

  # Include menus in footer
  #[[languages.en.params.footer_menus]]
  #  name = "Services"
  #  menu = "footer2"
  #[[languages.en.params.footer_menus]]
  #  name = "Links"
  #  menu = "footer1"

# Other params
[params]
  # Display post summaries instead of content in list templates (default: true)
  truncate = true